apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env : prod
    owner: ValeriySimachenkov
spec:
  selector:
    project: koad     
  ports:
    - name: app-listener
      protocol: TCP
      port: 80        
      targetPort: 80  
  type: LoadBalancer