apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-autoscaling
  labels:
    app: my-k8s-deployment
spec:
  selector:
    matchLabels:
      project: pja
  template:
    metadata:
      labels:
        project: pja
    spec:
      containers:
        - name: pja-web
          image: nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-deployment-autoscaling
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization 
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
apiVersion: v1 
kind: Service
metadata:
  name: my-autoscaling-pod-service
  labels:
    env   : prod
    owner : ValeriySimachenkov
spec:
  selector:
    project: pja
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80
      targetPort: 80
  type: LoadBalancer